// Curated list of IANA timezones grouped by region.
// Covers all UTC offsets with representative cities.
const Map<String, List<String>> timezonesByRegion = {
  'Africa': [
    'Africa/Abidjan',
    'Africa/Cairo',
    'Africa/Casablanca',
    'Africa/Johannesburg',
    'Africa/Lagos',
    'Africa/Nairobi',
    'Africa/Tunis',
  ],
  'Americas': [
    'America/Anchorage',
    'America/Argentina/Buenos_Aires',
    'America/Bogota',
    'America/Canada/Central',
    'America/Chicago',
    'America/Denver',
    'America/Halifax',
    'America/Los_Angeles',
    'America/Mexico_City',
    'America/New_York',
    'America/Sao_Paulo',
    'America/St_Johns',
    'America/Toronto',
    'America/Vancouver',
  ],
  'Antarctica': [
    'Antarctica/McMurdo',
    'Antarctica/Palmer',
    'Antarctica/Troll',
  ],
  'Arctic / Atlantic': [
    'Arctic/Longyearbyen',
    'Atlantic/Azores',
    'Atlantic/Canary',
    'Atlantic/Cape_Verde',
    'Atlantic/Reykjavik',
    'Atlantic/South_Georgia',
  ],
  'Asia': [
    'Asia/Baghdad',
    'Asia/Bangkok',
    'Asia/Colombo',
    'Asia/Dhaka',
    'Asia/Dubai',
    'Asia/Hong_Kong',
    'Asia/Jakarta',
    'Asia/Karachi',
    'Asia/Kathmandu',
    'Asia/Kolkata',
    'Asia/Kuala_Lumpur',
    'Asia/Manila',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Taipei',
    'Asia/Tehran',
    'Asia/Tokyo',
    'Asia/Yangon',
  ],
  'Australia / Pacific': [
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Darwin',
    'Australia/Hobart',
    'Australia/Lord_Howe',
    'Australia/Perth',
    'Australia/Sydney',
    'Pacific/Auckland',
    'Pacific/Fiji',
    'Pacific/Guam',
    'Pacific/Honolulu',
    'Pacific/Marquesas',
    'Pacific/Midway',
    'Pacific/Norfolk',
    'Pacific/Port_Moresby',
    'Pacific/Tahiti',
    'Pacific/Tongatapu',
  ],
  'Europe': [
    'Europe/Amsterdam',
    'Europe/Athens',
    'Europe/Berlin',
    'Europe/Brussels',
    'Europe/Bucharest',
    'Europe/Budapest',
    'Europe/Dublin',
    'Europe/Helsinki',
    'Europe/Istanbul',
    'Europe/Kiev',
    'Europe/Lisbon',
    'Europe/London',
    'Europe/Madrid',
    'Europe/Moscow',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Prague',
    'Europe/Rome',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Warsaw',
    'Europe/Zurich',
  ],
  'UTC': [
    'UTC',
  ],
};

// Returns a display-friendly name for an IANA zone string,
// e.g. "America/New_York" => "New York", "Europe/Berlin" => "Berlin".
String friendlyZoneName(String ianaZone) {
  final parts = ianaZone.split('/');
  return parts.last.replaceAll('_', ' ');
}