name: Deploy Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: subosito/flutter-action@v2.23.0
        with:
          flutter-version: '3.47.4'
          channel: stable

      - name: Install dependencies
        run: flutter pub get --enforce-lockfile

      - name: Collect build information
        run: |
          export FLUTTER_BIN=$(dirname $(which flutter))
          bash fastlane/build_info.sh

      - name: Build web
        run: flutter build web --release --base-href /epoch/ --dart-define-from-file=.build_info.env --no-pub

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
